###
# See which models are in the /models folder
GET http://localhost:8080/models


###
# Send a prompt, targetting a particular model
POST http://localhost:8080/v1/chat/completions 
content-Type: application/json

{
     "model": "gpt-3.5-turbo",
     "messages": [
          {
               "role": "user", 
               "content": "In the context of programming, what is Java and why would you use it?"
               }
          ],
     "temperature": 0.9
}

###

POST https://mockgpt.wiremockapi.cloud/v1/chat/completions 
content-Type: application/json

{
     "model": "gpt-3.5-turbo",
     "apiKey": "sk-hknuewz5we7u8ez4mi78khgfc3ch4iq0",
     "messages": [
          {
               "role": "user", 
               "content": "Hello World!"
               }
          ],
     "temperature": 0.9
}

###
POST http://localhost:8080/v1/chat/completions 
content-Type: application/json

{
     "model": "gpt-3.5-turbo",
     "messages": [
          {
               "role": "user", 
               "content": "Can you show me how to write a Java class that represents a Person? Respond with code and check for yourself that the class is correctly formed before you respond."
               }
          ],
     "temperature": 0.7
}

###
# Send a prompt, targetting a particular model
POST http://localhost:8080/v1/chat/completions 
content-Type: application/json

{
     "model": "gpt-3.5-turbo",
     "messages": [
          {
               "role": "user", 
               "content": "Who invented the SQL language and why? Give citations and sources."
               }
          ],
     "temperature": 0.9
}

